services:
  backend:
    build:
      context: ./QuoiRegarder_backend
    image: papemomath/quoiregarder_backend:latest
    container_name: backend
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:quoi_regarder
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - epic-4

  frontend:
    build:
      context: ./QuoiRegarder_frontend
    image: papemomath/quoiregarder_frontend:latest
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - epic-4

networks:
  epic-4:
    driver: bridge
